### ISSUE TITLE
Lisans Bilgisi

### ISSUE THREAD

**Issue by kodbilenadam** [utkusen/romtu#1]
Repo içerisinde lisans bilgisi eklenmemiş hala. Acaba ekleyebilir misiniz?

Teşekkürler!

**Comment by utkusen** [comment]
şu var ama gözünüzden kaçtı sanırım https://github.com/utkusen/romtu/blob/master/LICENSE

**Comment by kodbilenadam** [comment]
Üzgünüm, benim hatam :)
