### ISSUE TITLE
ImportError: cannot import name Counter

### ISSUE THREAD

**Issue by niyazialpay** [utkusen/romtu#3]
Merhaba, başarılı bir proje elinize sağlık ancak çalıştırırken bir hata ile karşılatım. Hata çıktısı aşağıdaki gibi. Acaba benim kullandığım python versiyonu mu desteklemiyor?

# python romtu.py 
Traceback (most recent call last):
  File "romtu.py", line 7, in <module>
    from collections import Counter
ImportError: cannot import name Counter

**Comment by utkusen** [comment]
requirements.txt dosyasında yer alan gerekli kütüphaneleri yükledikten sonra tekrar dener misiniz?
