### ISSUE TITLE
Lisans

### ISSUE THREAD

**Issue by erkantaylan** [utkusen/romtu#4]
Uygulamanızı hangi lisanslar altında sakladığınıza dair bir yazı koyabilir misiniz?

**Comment by mdegis** [comment]
@erkantaylan  fafb3e2 commit'deki [LICENSE](https://github.com/utkusen/romtu/blob/master/LICENSE) dosyasından alıntı:

```
The MIT License (MIT)

Copyright (c) 2016 Utku Sen
...
```
