### ISSUE TITLE
No handlers could be found for logger "gensim.models.word2vec"

### ISSUE THREAD

**Issue by bagerakbay** [utkusen/romtu#5]
Merhaba,

Ellerinize sağlık :) keyifle kurcalıyorum.

No handlers could be found for logger "gensim.models.word2vec"
Uyarısı alıyorum giriş yazısını yazdıktan sonra şiiri üretmiyor.

biraz daha kurcaladım, kelimeleri tarıyor ama uygun kelime bulamıyor, ufak bir kelime havuzunda takılı kalmış gibi davranıyor.

**Comment by utkusen** [comment]
merhaba. requirements.txt dosyasında belirtilen kütüphaneleri yüklediniz mi?
